### ISSUE TITLE
when clone,checkout failed.

### ISSUE THREAD

**Issue by jihe520** [QInzhengk/Math-Model-and-Machine-Learning#1]
Featurefatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by QInzhengk** [comment]
you try：clone时需要添加参数 -c core.symlinks=true 开启git对符号链接的支持

**Comment by jihe520** [comment]
>error: invalid path '数学建模/国赛数学建模竞赛/"华中杯"大学生数学建模挑战赛/10/2017第十届华中地区数学建模邀请赛_精英赛A
题/readme.md'
error: invalid path '数学建模/国赛数学建模竞赛/"华中杯"大学生数学建模挑战赛/10/2017第十届华中地区数学建模邀请赛_精英赛A 题/附件一/readme.md'

切换分支也会报错，大概率是文件路径，`/"华`，转义字符的问题？

**Comment by QInzhengk** [comment]
应该是

**Comment by QInzhengk** [comment]
# 忽略路径中的转义字符
git config --global core.protectNTFS false
# 禁用换行符转换
git config --global core.autocrlf false
# 中文文件名，乱码问题。设为false的话，就不会对0x80以上的字符进行quot
git config --global core.quotepath false
